### PR TITLE
fix(ZKUI-483): restore Metadata updates column in bucket list for XDM

### LINKED ISSUE #1132: Bucket list missing "Metadata updates" column for XDM environments
### Root Cause
In zenko-ui 4.1, the bucket list was rendered by a custom `BucketList.tsx` component that conditionally added a "Metadata updates" column when the XDM feature flag was enabled (`features.includes(XDM_FEATURE)`). This column displayed ingestion status ("Active" / "Paused") per bucket by calling `getLocationIngestionState()` with data from `instanceStatus.metrics['ingest-schedule'].states`.

In 4.2, the bucket list was migrated to use `DataBrowserUI` from `@scality/data-browser-library`, and the custom `BucketList.tsx` was replaced. The new architecture uses `extraBucketListColumns` (a `ColumnConfig[]` array) passed as a prop to `DataBrowserUI` to inject additional columns. However, during the migration, only "Storage Location" and "Data Used" columns were ported to `extraBucketListColumns` in `DataBrowser.tsx`. The "Metadata updates" column was never re-implemented, leaving the `getLocationIngestionState()` helper function as dead code in `src/react/utils/storageOptions.ts`.

All the underlying infrastructure for the feature still exists: the `XDM_FEATURE` constant, the `useConfig()` hook with `features[]`, the `useInstanceStatusQuery()` hook, and the `getLocationIngestionState()` utility. It was simply not wired into the new column injection architecture.
### Affected Component
- **Repo**: scality/zenko-ui
- **Path**: `src/react/databrowser/DataBrowser.tsx`
- **Version**: 4.2.15
### Evidence
```
src/react/databrowser/DataBrowser.tsx
└── L65: const extraBucketListColumns = useMemo(() => { ...  — The extraBucketListColumns array only defines 'Storage Location' and conditionally 'Data Used'. There is no 'Metadata updates' column entry, and no XDM feature check. In 4.1's BucketList.tsx, there was an additional conditional block: `if (features.includes(XDM_FEATURE)) { columns.push({ Header: 'Metadata updates', ... }) }` that is completely missing here.
src/react/utils/storageOptions.ts
└── L199: export function getLocationIngestionState(ingestionStates, locationName) { ...  — This helper function that maps ingestion states to display values ('Active'/'Paused') still exists in the 4.2 codebase but is dead code — it is not imported or called from anywhere. It was previously used by the 4.1 BucketList.tsx column renderer.
src/react/locations/hooks/useLocationReplicationControl.ts
└── L29: const ingestionLocationsStatuses = instanceStatus?.metrics?.['ingest-schedule']?.states; ...  — The ingestion status data pipeline is fully intact — useLocationReplicationControl reads 'ingest-schedule' states from instanceStatus and exposes ingestionStatus per location. This is used in the Locations section's PauseAndResume component but not in the bucket list.
src/js/config.ts
└── L1: export const XDM_FEATURE = 'XDM'; ...  — The XDM_FEATURE constant still exists and is used in other parts of the codebase (BucketCreateLocationEffects, LocationDetailsAwsCustom), confirming the XDM feature flag infrastructure is intact.
```
### Impact
Medium — Users in XDM environments have lost the ability to see the async metadata ingestion status (Active/Paused) at a glance from the bucket list view. They must navigate to the Locations section to check each location's ingestion status individually. This is a regression from Zenko UI 4.1 that affects all XDM deployments.
### Confidence
high
### Recommendation
Add a "Metadata updates" column to `extraBucketListColumns` in `src/react/databrowser/DataBrowser.tsx`, conditionally rendered when the XDM feature is enabled.

**1. Create a new column component** `src/react/databrowser/buckets/MetadataUpdatesColumn.tsx`:
```tsx
import type { Bucket } from '@scality/data-browser-library';
import { useInstanceStatusQuery } from '../../queries/instanceStatusQuery';
import { getLocationIngestionState } from '../../utils/storageOptions';

export const MetadataUpdatesColumn = ({ data }: { data: Bucket }) => {
  const { data: instanceStatus } = useInstanceStatusQuery();
  const ingestionStates = instanceStatus?.metrics?.['ingest-schedule']?.states;
  const { value } = getLocationIngestionState(ingestionStates, data.LocationConstraint);
  if (value === '-') return null;
  return <>{value}</>;
};
```

**2. Update `DataBrowser.tsx`** to add the XDM-conditional column:
- Import `useConfig` (already imported), `XDM_FEATURE` from `../../js/config`, and `MetadataUpdatesColumn`
- After the `isStorageManager` column push, add:
```tsx
const { features } = useConfig();
// ... inside the useMemo:
if (features.includes(XDM_FEATURE)) {
  columns.push({
    id: 'ingestion',
    header: 'Metadata updates',
    render: MetadataUpdatesColumn,
    width: '180px',
    cellStyle: { textAlign: 'right' },
  });
}
```
- Update the `useMemo` dependency array to include `features`

This follows the exact same pattern as `StorageLocationColumn` and `DataUsedColumn`, reuses the existing `getLocationIngestionState()` helper (currently dead code), and leverages the existing `useInstanceStatusQuery()` hook for data.

### PR DESCRIPTION
**Pull request by hervedombya**
## Summary
- Restores the "Metadata updates" column in the bucket list that was lost during the migration to `DataBrowserUI` in 4.2
- Column is conditionally displayed when XDM feature flag is enabled, matching 4.1 behavior
- Shows ingestion status (Active / Paused) per bucket, or a dash for non-applicable buckets

Closes #1132

## Test plan
- [ ] Verify the "Metadata updates" column appears in the bucket list when XDM is enabled
- [ ] Verify XDM buckets display "Active" or "Paused" status correctly
- [ ] Verify non-XDM buckets display a dash (—) in the column
- [ ] Verify the column does not appear when XDM feature is disabled

### CODE REVIEW

File: src/react/databrowser/buckets/MetadataUpdatesColumn.tsx [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import { Loader } from '@scality/core-ui';
+import { EmptyCell } from '@scality/core-ui/dist/components/tablev2/Tablev2.component';
+import type { Bucket } from '@scality/data-browser-library';
+import { useGetBucketLocation } from '@scality/data-browser-library';
+import { useInstanceStatusQuery } from '../../queries/instanceStatusQuery';
+import { getLocationIngestionState } from '../../utils/storageOptions';
+
+export const MetadataUpdatesColumn = ({ data }: { data: Bucket }) => {
```
Comment (MonPote) [inline src/react/databrowser/buckets/MetadataUpdatesColumn.tsx:8]: I guess we should add a test for this component ?

File: src/react/databrowser/DataBrowser.tsx [hunk 2]
```diff
@@ -73,6 +78,16 @@ export default function DataBrowser({ hideHeader = false }: { hideHeader?: boole
       },
     ];
 
+    if (features.includes(XDM_FEATURE)) {
```
Comment (MonPote) [inline src/react/databrowser/DataBrowser.tsx:81]: I guess we may want to add a test for that. To prevent "column in the bucket list that was lost during the migration"

File: src/react/databrowser/buckets/MetadataUpdatesColumn.tsx [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+    data: instanceStatus,
+    status: instanceStatusStatus,
+  } = useInstanceStatusQuery();
+
+  // 'pending' (react-query v5 via data-browser-library) vs 'loading' (react-query v3 via useInstanceStatusQuery)
+  if (locationStatus === 'pending' || instanceStatusStatus === 'loading') {
+    return <Loader size="small" />;
+  }
+
+  if (locationStatus === 'error') return <EmptyCell mr={0} />;
```
Comment (MonPote) [inline src/react/databrowser/buckets/MetadataUpdatesColumn.tsx]:
```suggestion
  if (locationStatus === 'error'  || instanceStatusStatus === 'error') return <EmptyCell mr={0} />;
```

File: src/react/databrowser/buckets/__tests__/MetadataUpdatesColumn.test.tsx [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+
+const mockUseInstanceStatusQuery = jest.fn();
+jest.mock('../../../queries/instanceStatusQuery', () => ({
+  useInstanceStatusQuery: () => mockUseInstanceStatusQuery(),
+}));
+
+const renderColumn = (bucketName = 'test-bucket') =>
+  render(
+    <ThemeProvider theme={theme}>
+      <MetadataUpdatesColumn data={{ Name: bucketName } as any} />
```
Comment (MonPote) [inline src/react/databrowser/buckets/__tests__/MetadataUpdatesColumn.test.tsx]: Is there a particular reason you use `any` here ?

File: src/react/databrowser/buckets/__tests__/MetadataUpdatesColumn.test.tsx [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+
+    expect(screen.queryByText('Active')).not.toBeInTheDocument();
+    expect(screen.queryByText('Paused')).not.toBeInTheDocument();
+  });
+
+  it('should not render status when instance status query fails', () => {
+    mockUseGetBucketLocation.mockReturnValue({
+      data: { LocationConstraint: 'test-xdm' },
+      status: 'success',
+    } as any);
```
Comment (MonPote) [inline src/react/databrowser/buckets/__tests__/MetadataUpdatesColumn.test.tsx:78]: I guess this one is very hard to type ?

File: src/react/databrowser/buckets/MetadataUpdatesColumn.tsx (hunk 3 above)
Comment (hervedombya) [reply src/react/databrowser/buckets/MetadataUpdatesColumn.tsx]: Currently when instance status errors, ingestionStates is undefined and getLocationIngestionState returns '-' which renders an EmptyCell anyway. But making it explicit is cleaner

File: src/react/databrowser/buckets/__tests__/MetadataUpdatesColumn.test.tsx (hunk 5 above)
Comment (hervedombya) [reply src/react/databrowser/buckets/__tests__/MetadataUpdatesColumn.test.tsx:78]: react-query return values fully in mocks adds noise with no real safety benefit

File: src/react/databrowser/buckets/__tests__/MetadataUpdatesColumn.test.tsx (hunk 4 above)
Comment (hervedombya) [reply src/react/databrowser/buckets/__tests__/MetadataUpdatesColumn.test.tsx]: just because aws sdk v3 have many optional fields but can be cast as Bucket actually

**Review by MonPote — APPROVED** [review]
LGTM
